from __future__ import annotations

import difflib
import errno
import json
import math
import os
import shutil
import tempfile
import threading
import warnings
from collections.abc import Mapping, Sequence
from contextlib import contextmanager
from dataclasses import dataclass
from functools import lru_cache
from importlib import resources
from pathlib import Path
from typing import Iterator, List, Optional, Tuple

from ._archive import fetch_archive, sha256_file

# NOTE: this module defines list() for `sdrbench.list()`. Never call the builtin `list(...)` here
# and annotate with typing.List, so that typing.get_type_hints() keeps working.

SDRBENCH_BIBTEX = """@inproceedings{zhao2020sdrbench,
  title     = {{SDRBench}: Scientific Data Reduction Benchmark for Lossy Compressors},
  author    = {Zhao, Kai and Di, Sheng and Liang, Xin and Li, Sihuan and Tao, Dingwen and Chen, Zizhong and Cappello, Franck},
  booktitle = {2020 IEEE International Conference on Big Data (Big Data)},
  pages     = {2716--2724},
  year      = {2020}
}"""


@lru_cache(maxsize=1)
def catalog() -> dict:
    """The bundled catalog (schema 2): datasets -> variants -> files, generated by the sync pipeline."""
    return json.loads(resources.files(__package__).joinpath("catalog.json").read_text())


def list(variants: bool = False) -> List[str]:  # noqa: A001 - mirrors the module-level verb users expect
    """Dataset names, e.g. ``['cesm-atm', 'exaalt', ...]``; with ``variants=True`` every
    ``"dataset/variant"`` (each accepted by :func:`dataset`)."""
    names = sorted(catalog()["datasets"])
    if not variants:
        return names
    return [f"{d}/{v}" for d in names for v in catalog()["datasets"][d]["variants"]]


def cache_dir(path=None) -> Path:
    """Cache root: ``path`` if given, else ``$SDRBENCH_CACHE``, else ``~/.cache/sdrbench``.
    Hugging Face downloads use the Hugging Face cache unless a path or ``$SDRBENCH_CACHE`` is set."""
    if path is not None:
        return Path(path)
    return Path(os.environ.get("SDRBENCH_CACHE", Path.home() / ".cache" / "sdrbench"))


def _human(n: float) -> str:
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if n < 1000 or unit == "TB":
            return f"{n:.0f} {unit}" if unit == "B" else f"{n:.1f} {unit}"
        n /= 1000


@dataclass(frozen=True)
class Field:
    """One array of a dataset variant (or, with ``dtype`` None, one non-array file).

    ``name`` is ``var`` or ``var/step``; ``path`` is the file in the Hugging Face repo
    (``<folder>/<original SDRBench file name>``)."""

    dataset: str
    variant: str
    name: str
    path: str
    nbytes: int  # size of the stored file
    sha256: str
    dtype: Optional[str] = None
    shape: Optional[Tuple[int, ...]] = None
    var: Optional[str] = None
    step: Optional[str] = None
    transpose: Optional[Tuple[int, ...]] = None  # derived layout: shape = stored array transposed
    file_shape: Optional[Tuple[int, ...]] = None  # shape of the stored file when it differs
    index: Optional[int] = None  # component view: the field is file[index] along axis 0
    roots: Tuple[str, ...] = ()  # local data directories searched before downloading

    def __repr__(self) -> str:
        if not self.dtype:
            return f"<sdrbench.Field {self.dataset}/{self.variant}:{self.name} (file, {_human(self.nbytes)})>"
        shape = "x".join(map(str, self.shape))
        return f"<sdrbench.Field {self.dataset}/{self.variant}:{self.name} {self.dtype} {shape} ({self.path})>"

    @property
    def filename(self) -> str:
        return self.path.rsplit("/", 1)[-1]

    @property
    def is_array(self) -> bool:
        return self.dtype is not None

    @property
    def stored_shape(self) -> Optional[Tuple[int, ...]]:
        """C-order shape of the bytes in the file: ``shape`` unless the field is a derived
        layout (transpose of the stored array) or one component of a stacked file."""
        return self.file_shape or self.shape

    @property
    def shape_fastest_first(self) -> Optional[Tuple[int, ...]]:
        """``shape`` reversed: the dimension order of command-line tools such as ``sz3 -3 x y z``."""
        return None if self.shape is None else tuple(reversed(self.shape))

    def download(self, dir=None, *, cache=None, source: Optional[str] = None) -> Path:
        """Download the stored file and return its local path.

        Without ``dir`` it stays in the cache; with ``dir`` it is saved as a plain file at
        ``<dir>/<path>`` (original SDRBench name). For derived layouts and component views the
        file is the stored one (see ``stored_shape``); use :meth:`save` for the array itself."""
        return _fetch(self, cache, source, local_dir=dir)

    def load(self, *, cache=None, mmap: bool = True, source: Optional[str] = None):
        """The array with its catalog dtype and C-order shape: a read-only memmap by default
        (``np.array(x)`` or ``mmap=False`` gives a writable copy). Derived (transposed) layouts
        are always an in-memory C-contiguous copy; component views are zero-copy memmaps."""
        import numpy as np

        if not self.dtype:
            raise ValueError(f"{self.path} is not a raw array; use .download() to get the file")
        p = self.download(cache=cache, source=source)
        if self.transpose:
            x = np.memmap(p, dtype=self.dtype, mode="r", shape=self.stored_shape)
            return np.ascontiguousarray(x.transpose(self.transpose))
        offset = 0
        if self.index is not None:
            offset = self.index * math.prod(self.shape) * np.dtype(self.dtype).itemsize
        if mmap:
            return np.memmap(p, dtype=self.dtype, mode="r", shape=self.shape, offset=offset)
        count = math.prod(self.shape)
        return np.fromfile(p, dtype=self.dtype, count=count, offset=offset).reshape(self.shape)

    def save(self, path, *, cache=None, source: Optional[str] = None) -> Path:
        """Write the array, exactly as returned by :meth:`load`, as a raw C-order binary file
        (for derived layouts and component views this materialises them)."""
        import numpy as np

        x = self.load(cache=cache, source=source)
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        np.ascontiguousarray(x).tofile(path)
        return path


class Series(Sequence):
    """The fields of one variable over time steps (or slabs), ordered by step."""

    def __init__(self, var: str, fields):
        self.var = var
        self._fields = sorted(fields, key=lambda f: _step_key(f.step))

    @property
    def steps(self) -> List[str]:
        return [f.step for f in self._fields]

    def __getitem__(self, i):
        if isinstance(i, str):
            for f in self._fields:
                if f.step == i:
                    return f
            raise KeyError(f"{self.var} has no step {i!r}; steps: {', '.join(self.steps[:10])} ...")
        return self._fields[i]

    def __len__(self) -> int:
        return len(self._fields)

    def load(self, i, **kw):
        return self[i].load(**kw)

    def stack(self, steps=slice(None), **kw):
        """``np.stack`` of the selected steps (a copy): shape (n, *field.shape)."""
        import numpy as np

        sel = self._fields[steps] if isinstance(steps, slice) else [self[s] for s in steps]
        total = sum(math.prod(f.shape) * np.dtype(f.dtype).itemsize for f in sel)
        if total > 4e9:
            warnings.warn(f"stacking {len(sel)} steps of {self.var}: {_human(total)} in memory", stacklevel=2)
        return np.stack([f.load(**kw) for f in sel])

    def concatenate(self, steps=slice(None), axis: int = 0, **kw):
        """``np.concatenate`` of the selected steps along ``axis`` (e.g. slabs of one field)."""
        import numpy as np

        sel = self._fields[steps] if isinstance(steps, slice) else [self[s] for s in steps]
        return np.concatenate([f.load(**kw) for f in sel], axis=axis)

    def __repr__(self) -> str:
        f = self._fields[0]
        return (f"<sdrbench.Series {f.dataset}/{f.variant}:{self.var} {len(self)} steps "
                f"[{self.steps[0]} ... {self.steps[-1]}], each {f.dtype} {'x'.join(map(str, f.shape))}>")


def _step_key(step):
    try:
        return (0, float(step), step)
    except (TypeError, ValueError):
        return (1, 0.0, str(step))


class Dataset(Mapping):
    """One variant of an SDRBench dataset: a read-only mapping from field name to numpy array.

    >>> nyx = sdrbench.dataset("nyx")
    >>> nyx.fields                 # array fields (physical variables)
    >>> t = nyx["temperature"]     # memmap, C order
    >>> hur = sdrbench.dataset("hurricane-isabel", "P")
    >>> hur.series("P").stack(slice(0, 4))   # (4, 100, 500, 500)

    Iterating values (``dict(ds)``, ``ds.values()``, ``ds.items()``) downloads every field."""

    def __init__(self, name: str, variant: Optional[str] = None, cache=None, root=None):
        if variant is None and "/" in name:
            name, variant = name.split("/", 1)
        name = _resolve(name, catalog()["datasets"], "dataset", key=_norm_dataset)
        meta = catalog()["datasets"][name]
        variants = [*meta["variants"]]
        if variant is None:
            variant = variants[0]
        else:  # also accept the Hugging Face / SDRBench folder name of a variant
            folders = {v.get("folder"): k for k, v in meta["variants"].items() if "transpose" not in v}
            variant = folders.get(variant, variant)
            variant = _resolve(variant, meta["variants"], f"{name} variant")
        self.name, self.variant, self.variants, self.cache = name, variant, variants, cache
        self.title = meta.get("title", name)
        self.provider = meta.get("source", "")
        self.repo = meta["repo"]
        self.revision = meta.get("revision")
        self._meta = meta
        v = meta["variants"][variant]
        self.folder = v.get("folder", variant)
        self.description = " ".join(x for x in (meta.get("description"), v.get("description")) if x)
        self.note = v.get("note")
        roots = _roots(root)
        tup = lambda x: tuple(x) if x else None
        self.files = [Field(name, variant, f.get("name") or f["path"][len(self.folder) + 1:], f["path"],
                            f["bytes"], f["sha256"], f.get("dtype"), tup(f.get("shape")), f.get("var"),
                            f.get("step"), tup(f.get("transpose")), tup(f.get("file_shape")), f.get("index"), roots)
                      for f in v["files"]]
        self._fields = {f.name: f for f in self.files if f.dtype}

    # mapping interface -------------------------------------------------------------
    @property
    def fields(self) -> List[str]:
        """Names of the array fields."""
        return [*self._fields]

    @property
    def extra_files(self) -> List[Field]:
        """Non-array files of the variant (text, readers, ADIOS/HDF5 files, ...)."""
        return [f for f in self.files if not f.dtype]

    @property
    def variables(self) -> List[str]:
        """Distinct physical variables, in catalog order."""
        return [*dict.fromkeys(f.var or f.name for f in self._fields.values())]

    @property
    def steps(self) -> List[str]:
        """Distinct time steps (or slabs), sorted; empty if the variant has none."""
        return sorted({f.step for f in self._fields.values() if f.step is not None}, key=_step_key)

    def series(self, var: str) -> Series:
        """All steps of one variable, ordered."""
        hits = [f for f in self._fields.values() if f.var == var] or \
               [f for f in self._fields.values() if (f.var or "").lower() == var.lower()]
        if not hits:
            raise KeyError(self._unknown(var, self.variables, "variable"))
        return Series(hits[0].var, hits)

    def field(self, name) -> Field:
        """Look up a file by field name (case-insensitive if unambiguous), ``(var, step)``,
        original file name, or repo path."""
        if isinstance(name, tuple):
            return self.series(name[0])[str(name[1])]
        if name in self._fields:
            return self._fields[name]
        for f in self.files:  # also accept the file name or repo path
            if name in (f.filename, f.path, f.path.split("/", 1)[-1]):
                return f
        hits = [f for n, f in self._fields.items() if n.lower() == name.lower()]
        if len(hits) == 1:
            return hits[0]
        if len(hits) > 1:
            raise KeyError(f"{name!r} is ambiguous in {self.name}/{self.variant}: {', '.join(f.name for f in hits)}")
        raise KeyError(self._unknown(name, self.fields, "field"))

    def _unknown(self, name, choices, what) -> str:
        msg = f"{self.name}/{self.variant} has no {what} {name!r}"
        close = difflib.get_close_matches(str(name), choices, n=3, cutoff=0.6)
        if close:
            msg += f"; did you mean {', '.join(map(repr, close))}?"
        for v, vv in self._meta["variants"].items():
            if v == self.variant:
                continue
            if v.lower() == str(name).lower():
                msg += f" ({name!r} is a variant: sdrbench.dataset({self.name!r}, {v!r}))"
                break
            if any(str(name) in (f.get("name"), f.get("var"), f["path"].rsplit("/", 1)[-1]) for f in vv["files"]):
                msg += f" ({name!r} is in variant {v!r})"
                break
        if not close and len(choices) <= 40:
            msg += f"; {what}s: {', '.join(choices)}"
        return msg

    def __getitem__(self, name):
        f = self.field(name)
        if not f.dtype:
            raise KeyError(f"{f.path} is not an array field; use ds.field({name!r}).download()")
        return f.load(cache=self.cache)

    def __iter__(self) -> Iterator[str]:
        return iter(self._fields)

    def __len__(self) -> int:
        return len(self._fields)

    def __contains__(self, name) -> bool:
        try:
            return bool(self.field(name).dtype)
        except KeyError:
            return False

    @property
    def nbytes(self) -> int:
        """Total size of the variant's stored files (what a full download fetches)."""
        return sum(f.nbytes for f in {f.path: f for f in self.files}.values())

    def download(self, dir=None, *, fields=None, source: Optional[str] = None, workers: int = 8) -> List[Path]:
        """Download files of this variant in parallel (all, or the given ``fields``).

        Files go to ``dir`` as plain files with their original names (``<dir>/<path>``, so
        ``sdrbench.dataset(name, root=dir)`` uses them later), or stay in the cache. Returns the
        local paths in the order of ``fields`` (or of ``self.files``)."""
        targets = [self.field(n) for n in fields] if fields else self.files
        unique = [*{f.path: f for f in targets}.values()]  # never fetch one file twice concurrently
        if workers <= 1 or len(unique) == 1:
            got = {f.path: f.download(dir, cache=self.cache, source=source) for f in unique}
        else:
            from concurrent.futures import ThreadPoolExecutor
            with ThreadPoolExecutor(min(workers, len(unique))) as pool:
                paths = pool.map(lambda f: f.download(dir, cache=self.cache, source=source), unique)
                got = dict(zip([f.path for f in unique], paths))
        return [got[f.path] for f in targets]

    def citation(self) -> str:
        """BibTeX for SDRBench, plus the data provider's own request and the exact data version."""
        parts = [SDRBENCH_BIBTEX]
        for k in ("citation_extra", "acknowledgment"):
            if self._meta.get(k):
                parts.append(f"% Requested by the data provider: {self._meta[k]}")
        from . import __version__
        parts.append(f"% Data: {self.title} ({self.name}/{self.variant}), Hugging Face {self.repo}"
                     f"@{self.revision or 'main'}, sdrbench=={__version__}")
        return "\n".join(parts)

    def __repr__(self) -> str:
        shapes = sorted({"x".join(map(str, f.shape)) for f in self._fields.values()})
        steps = f", {len(self.steps)} steps" if self.steps else ""
        extra = f", {len(self.extra_files)} other files" if self.extra_files else ""
        return (f"<sdrbench.Dataset {self.name}/{self.variant}: {len(self)} fields{steps}{extra}, "
                f"{', '.join(shapes[:3]) or '-'}{' ...' if len(shapes) > 3 else ''}, {_human(self.nbytes)}>")

    # Mapping equality would compare (downloaded) values; datasets compare by identity instead.
    __eq__ = object.__eq__
    __hash__ = object.__hash__


def _norm_dataset(s: str) -> str:
    return s.lower().replace("_", "-").replace(" ", "-")


def _resolve(name: str, choices, what: str, key=str.lower) -> str:
    """Exact match first, then a unique case-insensitive (or normalized) match."""
    if name in choices:
        return name
    hits = [c for c in choices if key(c) == key(name)]
    if len(hits) == 1:
        return hits[0]
    close = difflib.get_close_matches(name, [*choices], n=3, cutoff=0.5)
    hint = f"; did you mean {', '.join(map(repr, close))}?" if close else ""
    raise KeyError(f"unknown {what} {name!r}{hint} (available: {', '.join(choices)})")


def dataset(name: str, variant: Optional[str] = None, cache=None, root=None) -> Dataset:
    """Open a dataset (default: its first variant); ``"nyx/log"`` also selects a variant.

    ``root``: local directories (str, path or list; default ``$SDRBENCH_DATA``, ``:``-separated)
    searched for the files before downloading, e.g. an existing untarred SDRBench copy or an
    earlier ``ds.download(dir)``. Local files are used when their size matches the catalog."""
    return Dataset(name, variant, cache, root)


def load(name: str, field, variant: Optional[str] = None, *, cache=None, root=None, mmap: bool = True,
         source: Optional[str] = None):
    """Shortcut for ``dataset(name, variant)[field]``."""
    return dataset(name, variant, cache, root).field(field).load(cache=cache, mmap=mmap, source=source)


# local data --------------------------------------------------------------------------
def _roots(root) -> Tuple[str, ...]:
    if root is None:
        root = [r for r in os.environ.get("SDRBENCH_DATA", "").split(os.pathsep) if r]
    elif isinstance(root, (str, os.PathLike)):
        root = [root]
    return tuple(str(Path(r).expanduser()) for r in root)


@lru_cache(maxsize=16)
def _name_index(root: str) -> dict:
    """{(file name, size): path} of every file under a local root (built once per root)."""
    idx = {}
    for dp, _, fns in os.walk(root):
        for fn in fns:
            p = os.path.join(dp, fn)
            try:
                idx.setdefault((fn, os.path.getsize(p)), p)
            except OSError:
                pass
    return idx


def _find_local(f: Field) -> Optional[Path]:
    """A local copy of the stored file: <root>/<path>, <root>/<dataset>/<path>, or any file
    with the same name and size under the root (covers untarred SDRBench archives)."""
    for r in f.roots:
        for cand in (Path(r) / f.path, Path(r) / f.dataset / f.path):
            if cand.is_file() and cand.stat().st_size == f.nbytes:
                return cand
        hit = _name_index(r).get((f.filename, f.nbytes))
        if hit:
            return Path(hit)
    return None


# downloading ------------------------------------------------------------------------
def _hf_verified(path: Path, f: Field, local_dir) -> bool:
    """Integrity of a Hugging Face download against the catalog sha256. LFS files are content
    addressed (the cache blob name, or the etag recorded for a local_dir download, is the
    sha256), so this is usually free; anything else is hashed."""
    try:
        if local_dir is None:
            if path.resolve().name == f.sha256:
                return True
        else:
            meta = Path(local_dir) / ".cache" / "huggingface" / "download" / (f.path + ".metadata")
            lines = meta.read_text().splitlines() if meta.exists() else []
            if len(lines) > 1 and lines[1].strip().strip('"') == f.sha256:
                return True
    except OSError:
        pass
    return sha256_file(path) == f.sha256


def _download_hf(f: Field, cache, local_dir=None) -> Path:
    from huggingface_hub import hf_hub_download

    meta = catalog()["datasets"][f.dataset]
    kwargs = {}
    if cache is not None or "SDRBENCH_CACHE" in os.environ:
        kwargs["cache_dir"] = str(cache_dir(cache) / "hf")
    if local_dir is not None:
        kwargs["local_dir"] = str(local_dir)  # real file at <local_dir>/<path>, no cache copy
    # pinned to the Hugging Face commit the catalog was built from: later syncs cannot change it
    p = Path(hf_hub_download(repo_id=meta["repo"], filename=f.path, repo_type="dataset",
                             revision=meta.get("revision"), **kwargs))
    if not _hf_verified(p, f, local_dir):
        raise IOError(f"sha256 mismatch for {p} downloaded from {meta['repo']}")
    return p


_thread_locks: dict = {}
_thread_locks_guard = threading.Lock()


@contextmanager
def _globus_lock(target):
    """Exclusive lock for unpacking into ``target``: across threads and across processes."""
    from filelock import FileLock

    key = str(Path(target).resolve())
    with _thread_locks_guard:
        tl = _thread_locks.setdefault(key, threading.Lock())
    Path(key).parent.mkdir(parents=True, exist_ok=True)
    with tl, FileLock(key + ".lock"):
        yield


def _verified_marker(local: Path) -> Path:
    return local.with_name(local.name + ".sdrbench-ok")


def _download_globus(f: Field, cache) -> Path:
    v = catalog()["datasets"][f.dataset]["variants"][f.variant]
    arch = v["archive"]
    root = cache_dir(cache) / "globus" / f.dataset
    target = root / v.get("folder", f.variant)
    local = root / f.path
    marker = _verified_marker(local)
    with _globus_lock(target):  # one download/unpack per archive, even with parallel callers
        for attempt in range(2):
            if not local.exists():
                size = arch.get("bytes") or 0
                if size > 2e9:
                    warnings.warn(f"downloading the {size / 1e9:.1f} GB SDRBench archive {arch['url']} "
                                  f"from Globus to get {f.filename}", stacklevel=4)
                fetch_archive(arch["url"], target, expected_md5=arch.get("md5"))
            if not local.exists():
                raise FileNotFoundError(f"{f.path} not found in {arch['url']}")
            st = local.stat()
            stamp = f"{f.sha256} {st.st_size} {st.st_mtime_ns}"
            if marker.exists() and marker.read_text() == stamp:
                return local
            if st.st_size == f.nbytes and sha256_file(local) == f.sha256:
                marker.write_text(stamp)
                return local
            shutil.rmtree(target, ignore_errors=True)  # damaged cache: unpack again once
        raise IOError(f"sha256 mismatch for {local}: the archive on Globus does not match the catalog")


def _place(src: Path, local_dir, f: Field) -> Path:
    """Copy a cached or local file to <local_dir>/<path> (an independent plain file)."""
    if local_dir is None:
        return src
    dest = Path(local_dir) / f.path
    if dest.exists() and os.path.samefile(src, dest):
        return dest
    if dest.exists() and dest.stat().st_size == f.nbytes and sha256_file(dest) == f.sha256:
        return dest
    dest.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=dest.name + ".", suffix=".partial", dir=dest.parent)
    os.close(fd)
    try:
        shutil.copyfile(src, tmp)
        os.replace(tmp, dest)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)
    return dest


_LOCAL_ERRNOS = {errno.ENOSPC, errno.EACCES, errno.EROFS, getattr(errno, "EDQUOT", errno.ENOSPC)}


def _fetch(f: Field, cache, source: Optional[str], local_dir=None) -> Path:
    """Local data roots first, then Hugging Face; if the mirror cannot deliver, Globus."""
    source = source or os.environ.get("SDRBENCH_SOURCE", "auto")
    if source not in ("auto", "hf", "globus"):
        raise ValueError("source must be 'auto', 'hf' or 'globus'")
    if source == "auto":
        local = _find_local(f)
        if local is not None:
            return _place(local, local_dir, f)
    if source == "globus":
        return _place(_download_globus(f, cache), local_dir, f)
    try:
        return _download_hf(f, cache, local_dir)
    except Exception as e:
        offline = os.environ.get("HF_HUB_OFFLINE", "").lower() in ("1", "true", "yes")
        local_problem = isinstance(e, OSError) and e.errno in _LOCAL_ERRNOS  # disk full, permissions
        if source == "hf" or offline or local_problem:
            raise
        size = catalog()["datasets"][f.dataset]["variants"][f.variant]["archive"].get("bytes") or 0
        warnings.warn(f"Hugging Face download of {f.path} failed ({type(e).__name__}: {e}); falling back "
                      f"to the original SDRBench archive on Globus ({size / 1e9:.1f} GB)", stacklevel=3)
        return _place(_download_globus(f, cache), local_dir, f)
