from __future__ import annotations

import fnmatch
import json
import os
from dataclasses import dataclass
from functools import lru_cache
from importlib import resources
from pathlib import Path

from .archive import fetch_archive, sha256_file

SOURCES = ("hf", "globus")


@dataclass(frozen=True)
class FileInfo:
    dataset: str
    variant: str
    path: str  # path inside the Hugging Face repo, e.g. "512x512x512/temperature.f32"
    bytes: int
    sha256: str
    dtype: str | None  # numpy dtype string such as "<f4"; None for non-array files
    shape: tuple | None

    @property
    def name(self) -> str:
        return self.path.rsplit("/", 1)[-1]


@lru_cache(maxsize=1)
def catalog() -> dict:
    """The bundled dataset catalog (generated by the sync pipeline)."""
    return json.loads(resources.files(__package__).joinpath("catalog.json").read_text())


def datasets() -> list[str]:
    """Names of all available datasets, e.g. ``['cesm-atm', 'hacc', 'nyx', ...]``."""
    return sorted(catalog()["datasets"])


def info(dataset: str) -> dict:
    """Description, source, citation and variants of one dataset."""
    try:
        return catalog()["datasets"][dataset]
    except KeyError:
        raise KeyError(f"unknown dataset {dataset!r}; available: {', '.join(datasets())}") from None


def variants(dataset: str) -> list[str]:
    return list(info(dataset)["variants"])


def files(dataset: str, pattern: str = "*", variant: str | None = None,
          arrays_only: bool = False) -> list[FileInfo]:
    """Files of a dataset whose repo path or file name matches ``pattern`` (glob)."""
    out = []
    for vname, v in info(dataset)["variants"].items():
        if variant is not None and vname != variant:
            continue
        for f in v["files"]:
            if not (fnmatch.fnmatch(f["path"], pattern) or fnmatch.fnmatch(f["path"].rsplit("/", 1)[-1], pattern)):
                continue
            if arrays_only and not f.get("dtype"):
                continue
            out.append(FileInfo(dataset, vname, f["path"], f["bytes"], f["sha256"],
                                f.get("dtype"), tuple(f["shape"]) if f.get("shape") else None))
    return out


def _one(dataset: str, path: str) -> FileInfo:
    hits = files(dataset, path)
    exact = [f for f in hits if f.path == path]
    hits = exact or hits
    if len(hits) != 1:
        names = ", ".join(f.path for f in hits[:10]) or "none"
        raise ValueError(f"{path!r} matches {len(hits)} files in {dataset} ({names}); use the full path")
    return hits[0]


def cache_dir(path=None) -> Path:
    if path is not None:
        return Path(path)
    return Path(os.environ.get("SDRBENCH_CACHE", Path.home() / ".cache" / "sdrbench"))


def _download_hf(f: FileInfo, cache) -> Path:
    from huggingface_hub import hf_hub_download

    repo = info(f.dataset)["repo"]
    kwargs = {"cache_dir": str(cache / "hf")} if cache is not None else {}
    return Path(hf_hub_download(repo_id=repo, filename=f.path, repo_type="dataset", **kwargs))


def _download_globus(f: FileInfo, cache) -> Path:
    v = info(f.dataset)["variants"][f.variant]
    root = cache_dir(cache) / "globus" / f.dataset
    local = root / f.path
    if not local.exists():
        arch = v["archive"]
        fetch_archive(arch["url"], root / f.variant, expected_md5=arch.get("md5"))
    if not local.exists():
        raise FileNotFoundError(f"{f.path} not found in {v['archive']['url']}")
    return local


def download(dataset: str, path: str, source: str = "hf", cache=None, verify: bool | None = None) -> Path:
    """Download one file and return its local path.

    ``path`` is a repo path (``"512x512x512/temperature.f32"``) or a unique file
    name/glob (``"temperature.f32"``). ``source="hf"`` fetches the single file from
    Hugging Face; ``source="globus"`` fetches the original SDRBench archive from
    Globus, unpacks it into the cache, and returns the file from there.
    ``verify`` checks the sha256 (default: on for Globus, off for HF, which
    already verifies content hashes).
    """
    if source not in SOURCES:
        raise ValueError(f"source must be one of {SOURCES}")
    f = _one(dataset, path)
    local = _download_hf(f, cache) if source == "hf" else _download_globus(f, cache)
    if verify if verify is not None else source == "globus":
        got = sha256_file(local)
        if got != f.sha256:
            raise IOError(f"sha256 mismatch for {local}: got {got}, expected {f.sha256}")
    return local


def load(dataset: str, path: str, source: str = "hf", cache=None, mmap: bool = True):
    """Download a file (if needed) and return it as a numpy array with its catalog shape."""
    import numpy as np

    f = _one(dataset, path)
    if not f.dtype:
        raise ValueError(f"{f.path} is not a raw array file; use download() instead")
    local = download(dataset, f.path, source=source, cache=cache)
    shape = f.shape or (f.bytes // np.dtype(f.dtype).itemsize,)
    if mmap:
        return np.memmap(local, dtype=f.dtype, mode="r", shape=shape)
    return np.fromfile(local, dtype=f.dtype).reshape(shape)
