from __future__ import annotations

import json
import os
import shutil
import threading
import warnings
from dataclasses import dataclass
from functools import lru_cache
from importlib import resources
from pathlib import Path
from typing import Iterator

from .archive import fetch_archive, sha256_file

@lru_cache(maxsize=1)
def catalog() -> dict:
    """The bundled dataset catalog (generated by the sync pipeline)."""
    return json.loads(resources.files(__package__).joinpath("catalog.json").read_text())


# NOTE: this module defines list() for `sdrbench.list()`; never call the builtin `list(...)` here.
def list() -> list[str]:  # noqa: A001 - mirrors the module-level verb users expect
    """Names of all datasets, e.g. ``['cesm-atm', 'exaalt', 'hacc', 'nyx', ...]``."""
    return sorted(catalog()["datasets"])


def cache_dir(path=None) -> Path:
    if path is not None:
        return Path(path)
    return Path(os.environ.get("SDRBENCH_CACHE", Path.home() / ".cache" / "sdrbench"))


@dataclass(frozen=True)
class Field:
    """One file of a dataset. ``dtype``/``shape`` are None for non-array files (text, HDF5, ADIOS)."""

    dataset: str
    variant: str
    name: str
    path: str  # path inside the Hugging Face repo
    nbytes: int
    sha256: str
    dtype: str | None
    shape: tuple | None
    transpose: tuple | None = None  # set for derived layouts: stored file = transpose of `shape`

    @property
    def filename(self) -> str:
        return self.path.rsplit("/", 1)[-1]

    def download(self, dir=None, *, cache=None, source: str | None = None) -> Path:
        """Download the file and return its local path.

        Without ``dir`` the file stays in the cache. With ``dir`` it is saved as a plain file
        under its original SDRBench name, ``<dir>/<variant>/<file>``, and that path is returned.
        """
        return _fetch(self, cache, source, local_dir=dir)

    def load(self, cache=None, mmap: bool = True, source: str | None = None):
        """The file as a numpy array with its catalog dtype and C-order shape."""
        import numpy as np

        if not self.dtype:
            raise ValueError(f"{self.path} is not a raw array; use .download() to get the file")
        p = self.download(cache=cache, source=source)
        if self.transpose:  # derived layout: read the stored order, return a C-contiguous copy
            stored = tuple(self.shape[self.transpose.index(i)] for i in range(len(self.shape)))
            x = np.memmap(p, dtype=self.dtype, mode="r", shape=stored)
            return np.ascontiguousarray(x.transpose(self.transpose))
        if mmap:
            return np.memmap(p, dtype=self.dtype, mode="r", shape=self.shape)
        return np.fromfile(p, dtype=self.dtype).reshape(self.shape)


class Dataset:
    """One variant of an SDRBench dataset; a read-only mapping from field name to numpy array.

    >>> nyx = sdrbench.dataset("nyx")
    >>> nyx.fields
    >>> t = nyx["temperature"]
    """

    def __init__(self, name: str, variant: str | None = None, cache=None):
        if variant is None and "/" in name:
            name, variant = name.split("/", 1)
        name = _resolve(name, catalog()["datasets"], "dataset", key=_norm_dataset)
        meta = catalog()["datasets"][name]
        variants = [*meta["variants"]]
        variant = variants[0] if variant is None else _resolve(variant, meta["variants"], f"{name} variant")
        self.name, self.variant, self.variants, self.cache = name, variant, variants, cache
        self.title = meta.get("title", name)
        self.description = meta.get("description", "")
        self.source_info = meta.get("source", "")
        self.repo = meta["repo"]
        self._archive = meta["variants"][variant]["archive"]
        # field names (physical variable names) are assigned by the sync pipeline; other files keep their path
        stored = meta["variants"][variant].get("folder", variant)  # folder on Hugging Face
        self.note = meta["variants"][variant].get("note")
        self.files = [Field(name, variant, f.get("name") or f["path"][len(stored) + 1:], f["path"], f["bytes"],
                            f["sha256"], f.get("dtype"), tuple(f["shape"]) if f.get("shape") else None,
                            tuple(f["transpose"]) if f.get("transpose") else None)
                      for f in meta["variants"][variant]["files"]]
        self._fields = {f.name: f for f in self.files if f.dtype}

    # mapping interface -------------------------------------------------------------
    @property
    def fields(self) -> list[str]:
        return [*self._fields]

    def field(self, name: str) -> Field:
        """Look up a field by name (case-insensitive if unambiguous), file name, or repo path."""
        if name in self._fields:
            return self._fields[name]
        for f in self.files:  # also accept the file name or repo path
            if name in (f.filename, f.path, f.path.split("/", 1)[-1]):
                return f
        hits = [f for n, f in self._fields.items() if n.lower() == name.lower()]
        if len(hits) == 1:
            return hits[0]
        if len(hits) > 1:
            raise KeyError(f"{name!r} is ambiguous in {self.name}/{self.variant}: {', '.join(f.name for f in hits)}")
        raise KeyError(f"{self.name}/{self.variant} has no field {name!r}; fields: {', '.join(self.fields)}")

    def __getitem__(self, name: str):
        return self.field(name).load(self.cache)

    def __iter__(self) -> Iterator[str]:
        return iter(self._fields)

    def __len__(self) -> int:
        return len(self._fields)

    def __contains__(self, name) -> bool:
        return name in self._fields

    def keys(self):
        return self.fields

    def items(self):
        """(name, array) pairs; each file is downloaded when reached."""
        for n in self._fields:
            yield n, self[n]

    @property
    def nbytes(self) -> int:
        return sum(f.nbytes for f in self.files)

    def download(self, dir=None, *, fields=None, source: str | None = None, workers: int = 8) -> list[Path]:
        """Download files of this variant in parallel (all, or the given ``fields``).

        Files go to ``dir`` as plain files under their original names, or stay in the cache.
        Returns the local paths in the order of ``fields`` (or of ``self.files``)."""
        targets = [self.field(n) for n in fields] if fields else [f for f in self.files if not f.transpose] or self.files
        if workers <= 1 or len(targets) == 1:
            return [f.download(dir, cache=self.cache, source=source) for f in targets]
        from concurrent.futures import ThreadPoolExecutor
        with ThreadPoolExecutor(min(workers, len(targets))) as pool:
            return [*pool.map(lambda f: f.download(dir, cache=self.cache, source=source), targets)]

    def __repr__(self) -> str:
        shapes = sorted({"x".join(map(str, f.shape)) for f in self._fields.values()})
        return (f"<sdrbench.Dataset {self.name}/{self.variant}: {len(self)} fields, "
                f"{', '.join(shapes[:3])}{' ...' if len(shapes) > 3 else ''}, {self.nbytes / 1e9:.2f} GB>")


def _norm_dataset(s: str) -> str:
    return s.lower().replace("_", "-").replace(" ", "-")


def _resolve(name: str, choices, what: str, key=str.lower) -> str:
    """Exact match first, then a unique case-insensitive (or normalized) match."""
    if name in choices:
        return name
    hits = [c for c in choices if key(c) == key(name)]
    if len(hits) == 1:
        return hits[0]
    raise KeyError(f"unknown {what} {name!r}; available: {', '.join(choices)}")


def dataset(name: str, variant: str | None = None, cache=None) -> Dataset:
    """Open a dataset (default: its first variant). ``"nyx/512x512x512_log"`` also selects a variant."""
    return Dataset(name, variant, cache)


def load(name: str, field: str, variant: str | None = None, cache=None, mmap: bool = True):
    """Shortcut for ``dataset(name, variant)[field]``."""
    return dataset(name, variant, cache).field(field).load(cache, mmap)


# downloading ------------------------------------------------------------------------
def _download_hf(f: Field, cache, local_dir=None) -> Path:
    from huggingface_hub import hf_hub_download

    repo = catalog()["datasets"][f.dataset]["repo"]
    kwargs = {"cache_dir": str(Path(cache) / "hf")} if cache is not None else {}
    if local_dir is not None:
        kwargs["local_dir"] = str(local_dir)  # real file at <local_dir>/<path>, no cache copy
    return Path(hf_hub_download(repo_id=repo, filename=f.path, repo_type="dataset", **kwargs))


_archive_locks: dict = {}
_locks_guard = threading.Lock()


def _download_globus(f: Field, cache) -> Path:
    v = catalog()["datasets"][f.dataset]["variants"][f.variant]
    arch = v["archive"]
    root = cache_dir(cache) / "globus" / f.dataset
    local = root / f.path
    with _locks_guard:  # one download/unpack per archive, even with parallel callers
        lock = _archive_locks.setdefault(arch["url"], threading.Lock())
    with lock:
        if not local.exists():
            fetch_archive(arch["url"], root / v.get("folder", f.variant), expected_md5=arch.get("md5"))
    if not local.exists():
        raise FileNotFoundError(f"{f.path} not found in {arch['url']}")
    if sha256_file(local) != f.sha256:
        raise IOError(f"sha256 mismatch for {local} (archive on Globus changed?)")
    return local


def _place(src: Path, local_dir, f: Field) -> Path:
    """Put a cached Globus file at <local_dir>/<path> (hard link if possible, else copy)."""
    if local_dir is None:
        return src
    dest = Path(local_dir) / f.path
    if dest.exists() and dest.stat().st_size == f.nbytes:
        return dest
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest.with_name(dest.name + ".partial")
    tmp.unlink(missing_ok=True)
    try:
        os.link(src, tmp)
    except OSError:
        shutil.copyfile(src, tmp)
    os.replace(tmp, dest)
    return dest


def _fetch(f: Field, cache, source: str | None, local_dir=None) -> Path:
    """Hugging Face first; if that fails, the original archive on Globus."""
    source = source or os.environ.get("SDRBENCH_SOURCE", "auto")
    if source not in ("auto", "hf", "globus"):
        raise ValueError("source must be 'auto', 'hf' or 'globus'")
    if source == "globus":
        return _place(_download_globus(f, cache), local_dir, f)
    try:
        return _download_hf(f, cache, local_dir)
    except Exception as e:  # network error, HF outage, file missing on the mirror, ...
        if source == "hf":
            raise
        warnings.warn(f"Hugging Face download of {f.path} failed ({type(e).__name__}: {e}); "
                      f"falling back to the original SDRBench archive on Globus", stacklevel=3)
        return _place(_download_globus(f, cache), local_dir, f)
